version: '4.5'
services:
  wtf_mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27044:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container: